# Configurações do Servidor
spring.application.name=api
server.port=8888

# Configurações da Base de Dados PostgreSQL
spring.datasource.url=jdbc:postgresql://pooled.db.prisma.io:5432/postgres?sslmode=require
spring.datasource.username=e9c9c2a2c60d4b5952f6f5a000747710ca4d750ce0824f5b18a2502d80473858
spring.datasource.password=sk_3CZta4nU27F3ZzZ2OD3ch
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true