spring.application.name=api

# Configura a porta da aplicação
server.port=8888

# Desabilita (por enquanto) o acesso a banco de dados
#spring.autoconfigure.exclude=org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration

spring.jpa.hibernate.ddl-auto=validate

spring.datasource.url=jdbc:postgresql://pooled.db.prisma.io:5432/postgres?sslmode=require

spring.datasource.username=57267d746f35b36eb0c71feb9354ed4609f83f1a6af23a7942372dc1272b4ee5
spring.datasource.password=sk_zBwLBdI9OSLqOqLBRtpr8

