spring.application.name=api

# Configura a porta da aplicação
server.port=8888

# Configurações do JPA e Base de Dados
spring.jpa.hibernate.ddl-auto=validate

# Conexão Direta ao Prisma (sem pooling)
spring.datasource.url=jdbc:postgresql://db.prisma.io:5432/postgres?sslmode=require
spring.datasource.username=e9c9c2a2c60d4b5952f6f5a000747710ca4d750ce0824f5b18a2502d80473858
spring.datasource.password=sk_Mv2Lygh5VftwSsusdf9Y8
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuração do Flyway
spring.flyway.enabled=true